"""add cycling workout support

Revision ID: 8cfa5d7099b1
Revises: c060b17d692a
Create Date: 2026-07-30 21:42:09.832889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfa5d7099b1'
down_revision: Union[str, None] = 'c060b17d692a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE workout_type ADD VALUE IF NOT EXISTS 'CYCLING'")
    op.create_table('cycling_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Integer(), nullable=True),
    sa.Column('route_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycling_sessions')
    # ### end Alembic commands ###
